/**
 * @packageDocumentation
 * @module api.functional.subscribe.consumers
 */
//================================================================
import { AesPkcs5 } from "./../../../__internal/AesPkcs5";
import { Fetcher } from "./../../../__internal/Fetcher";
import { Primitive } from "./../../../Primitive";
import type { IConnection } from "./../../../IConnection";

import type { IIamportSubscription } from "./../../../structures/IIamportSubscription";
import type { IIamportResponse } from "./../../../structures/IIamportResponse";


/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller FakeIamportSubscribeConsumersController.store()
 * @path POST /subscribe/consumers/:customer_uid
 */
export function store
    (
        connection: IConnection,
        customer_uid: string,
        input: Primitive<store.Input>
    ): Promise<store.Output>
{
    return Fetcher.fetch
    (
        connection,
        store.CONFIG,
        store.METHOD,
        store.path(customer_uid),
        input
    );
}
export namespace store
{
    export type Input = Primitive<IIamportSubscription.IStore>;
    export type Output = Primitive<IIamportResponse<IIamportSubscription>>;


    export const METHOD = "POST";
    export const PATH = "/subscribe/consumers/:customer_uid";
    export const CONFIG = {
        input_encrypted: false,
        output_encrypted: false,
    };

    export function path(customer_uid: string): string
    {
        return `/subscribe/consumers/${customer_uid}`;
    }
}

/**
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller FakeIamportSubscribeConsumersController.erase()
 * @path DELETE /subscribe/consumers/:customer_uid
 */
export function erase
    (
        connection: IConnection,
        customer_uid: string
    ): Promise<erase.Output>
{
    return Fetcher.fetch
    (
        connection,
        erase.CONFIG,
        erase.METHOD,
        erase.path(customer_uid)
    );
}
export namespace erase
{
    export type Output = Primitive<IIamportResponse<IIamportSubscription>>;


    export const METHOD = "DELETE";
    export const PATH = "/subscribe/consumers/:customer_uid";
    export const CONFIG = {
        input_encrypted: false,
        output_encrypted: false,
    };

    export function path(customer_uid: string): string
    {
        return `/subscribe/consumers/${customer_uid}`;
    }
}



//---------------------------------------------------------
// TO PREVENT THE UNUSED VARIABLE ERROR
//---------------------------------------------------------
AesPkcs5;
Fetcher;
Primitive;
